//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnABot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionFile
    {
        public int QuestionId { get; set; }
        public int ParentId { get; set; }
        public string Question { get; set; }
        public string Value { get; set; }
        public int QuestionLevel { get; set; }
        public string AnswerType { get; set; }
        public string Answer { get; set; }
        public int Seq { get; set; }
        public bool IsShow { get; set; }
    }
}
